openapi: 3.0.0
info: 
  title: Movie Queen API
  description: Umm... knock, knock...JK. This is a doc all about how to not get twisted upside down when working with the Movie Queen API.
  version: 0.0.1

server:
  - url: https://idk-yet-but-its-the-base-url
    description: tbd
  - url: http://idk-still
    description: ....

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          example: 4
        name:
          type: string
          example: Arthur Dent
      # Both properties are required
      required:  
        - id
        - name

paths:
  /users:
    get:
      summary: Returns a list of users.
      description: Optional extended description in CommonMark or HTML.
      responses:
        '200':    # status code
          description: A JSON array of user names
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string

  /users/{userId}:
      get:
        summary: Returns a user by ID.
        parameters:
          - name: userId
            in: path
            required: true
            description: Parameter description in CommonMark or HTML.
            schema:
              type : integer
              format: int64
              minimum: 1
        responses: 
          '200':
            description: OK
            content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'  

  /users:
    post:
      summary: Creates a user.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
      responses: 
        '201':
          description: Created